server:
  port: 8080
  context-path: /ems
---
spring:
  mvc:
    date-format: yyyy-MM-dd
---
# 数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_manager_system?useSSL=false
    username: root
    password: root
---
# 模板
spring:
  thymeleaf: 
    mode: LEGACYHTML5
    cache: false
    

---
mybatis:
  type-aliases-package: com.joe.ems.domain
  mapper-locations:
    - classpath:com/joe/ems/mapper/*.xml